jobs:
  include:
    - os: linux
      dist: bionic
      sudo: required
    - os: linux
      dist: focal
      sudo: required
      apt:
        update: true
        packages:
          - binutils 
          - git 
          - gnupg2 
          - libc6-dev 
          - libcurl4 
          - libedit2 
          - libgcc-9-dev 
          - libpython2.7 
          - libsqlite3-0 
          - libstdc++-9-dev 
          - libxml2 
          - libz3-dev 
          - pkg-config 
          - tzdata 
          - zlib1g-dev
    - os: osx
      osx_image: xcode11.4
env:
  global:
  - FRAMEWORK_NAME=Base32Crockford
  - SWIFT_VER=5.2.4
before_install:
  - bash -e ./Scripts/before_install.sh
script:
  - bash -e ./Scripts/script.sh
