matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
      install:
        - sudo apt-get update
        - sudo apt-get install gcc-4.9 clang
        - mkdir swift
        - curl https://swift.org/builds/swift-4.2.1-release/ubuntu1804/swift-4.2.1-RELEASE/swift-4.2.1-RELEASE-ubuntu18.04.tar.gz -s | tar xz -C swift &> /dev/null
        - export PATH="$(pwd)/swift/swift-4.2.1-RELEASE-ubuntu18.04/usr/bin:$PATH"
      script:
        - swift package update
        - swift test
#     - os: osx
#       language: objective-c
#       osx_image: xcode10.1
#       script:
#         - swift package update
#         - swift test
