jobs:
  include:
    - os: linux
      dist: 
        - focal
        - bionic
      sudo: required
      arch:
        - amd64
        - arm64
    - os: osx
      osx_image: 
        - xcode11.4
        - xcode11.5
env:
  global:
  - FRAMEWORK_NAME=Base32Crockford
  - SWIFT_VER=5.2.4
before_install:
  - bash -e ./Scripts/before_install.sh
script:
  - bash -e ./Scripts/script.sh
